print("it\'s alright")
print("My name is \"VISHESH SINGHAL\"")
print("MY name is \n vishesh singhal")
print("\\newton is stupid")
print("my name is vishesh singhal\t and i am a good boy")
print("my \fname is vishesh singhal")
print("my name is \bvishesh singhal")
print("my name is \rvishesh singhal")
print("\110\145\154\154\157")
print("\x48\x65\x6c\x6c\x6f")